version: "3.7"
services:
    kaggle:
            image: gcr.io/kaggle-images/python:latest
            environment: 
                - JUPYTER_TOKEN=dArHkvO6bF@fpEGC@yBqqJ0ezm80j3ewerNq
            command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
            volumes: 
                - .:/workspace
            ports: 
                - 8888:8888
                - 6006:6006
            container_name: kaggle